services:
  api:
    build: pd311_web_api/
    image: mishkanchikk/back
    container_name: "api"
    ports:
      - "7223:8080"
    environment:
      - ConnectionStrings__NpgsqlLocal=User ID=postgres;Password=qwerty;Host=db;Port=5432;Database=pd311_web_api;
      - Cors__AllowedOrigins=http://34.68.48.94
    volumes:
      - api_files:/app/wwwroot
    networks:
      - api_nt

  front:
    build:
      context: dashboard/
      args:
        REACT_APP_API_URL: http://34.68.48.94:7223/api/
        REACT_APP_IMAGES_URL: http://34.68.48.94:7223/images/
    image: mishkanchikk/front
    container_name: "front"
    ports:
      - "80:3000"
    depends_on:
      - "api"

networks:
  api_nt:

volumes:
  api_files:
    name: "pd311_api"